Alistyle/urls.py
from django.contrib import admin
from django.urls import path, include
from asosiy.views import LoginsizView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('asosiy/', include("asosiy.urls")),
    path("buyurtma/", include("buyurtma.urls")),
    path("user/", include("userapp.urls")),
    path('', LoginsizView.as_view())
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asosiy/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('bolimlar/', Bolimlar.as_view(), name='bolimlar'),
    path("mahsulotlar/<int:pk>/", Mahsulotlar.as_view(), name='mahsulotlar'),
    path('mahsulot/<int:pk>/', MahsulotView.as_view(), name='mahsulot'),
]

buyurtma/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('savat/', SavatlarView.as_view(), name='savat'),
    path('tanlangan/', TanlanganlarView.as_view(), name='tanlangan'),
    path('buyurtmalar/', BuyurtmalarView.as_view(), name='buyurtma'),
]

userapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
    path('tasdiqlash/', Tasdiqlash.as_view(), name='tasdiqlash'),
]

asosiy/models.py
from django.db import models
from userapp.models import Profile


class Bolim(models.Model):
    nom = models.CharField(max_length=150)
    rasm = models.FileField(upload_to="bolim")
    def __str__(self):
        return self.nom

class Mahsulot(models.Model):
    nom = models.CharField(max_length=150)
    narx = models.PositiveBigIntegerField()
    chegirma = models.PositiveBigIntegerField()
    batafsil = models.TextField()
    brend = models.CharField(max_length=150)
    kafolat = models.IntegerField()
    yetkazish = models.IntegerField()
    mavjud = models.BooleanField(default=False)
    bolim = models.ForeignKey(Bolim, on_delete=models.CASCADE)
    davlat = models.CharField(max_length=150)

class Media(models.Model):
    rasm = models.FileField()
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.CASCADE)

class Izoh(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.CASCADE)
    matn = models.TextField()
    rating = models.IntegerField()
    sana = models.DateField()

    def __str__(self):
        return self.matn

buyurtma/models.py
from django.db import models

# Create your models here.

userapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    ism = models.CharField(max_length=150)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tel_raqam = models.CharField(max_length=15, blank=True)
    jins = models.CharField(max_length=6)
    shahar = models.CharField(max_length=150)
    davlat = models.CharField(max_length=150)
    sms_kod = models.CharField(max_length=150)
    tasdiqlangan = models.BooleanField(default=False)

    def __str__(self):
        return self.ism

asosiy/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import *
from django.contrib.auth import authenticate, login, logout
# Create your views here.

class HomeView(View):
    def get(self, request):
        content = {
            'bolimlar': Bolim.objects.all()[:7],
            "mahsulotlar": Mahsulot.objects.all()
        }
        return render(request, 'page-index.html', content)

class LoginsizView(View):
    def get(self, request):
        return render(request, 'page-index-2.html')

class Bolimlar(View):
    def get(self, request):
        content = {
            "bolimlar": Bolim.objects.all()
        }
        return render(request, 'page-category.html', content)

class Mahsulotlar(View):
    def get(self, request, pk):
        content = {
            "mahsulotlar": Mahsulot.objects.filter(bolim__id=pk)
        }
        return render(request, 'page-listing-grid.html', content)

class MahsulotView(View):
    def get(self, request, pk):
        content = {
            "izohlar": Izoh.objects.filter(mahsulot_id=pk),
            "mahsulot": Mahsulot.objects.get(id=pk)
        }
        return render(request, 'page-detail-product.html', content)

buyurtma/views.py
from django.shortcuts import render
from django.views import View
class SavatlarView(View):
    def get(self, request):
        return render(request, 'page-shopping-cart.html')

class TanlanganlarView(View):
    def get(self, request):
        return render(request, 'page-profile-wishlist.html')

class BuyurtmalarView(View):
    def get(self, request):
        return render(request, 'page-profile-orders.html')

userapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import *
from random import randint
from eskiz.client import SMSClient
# Create your views here.

class LoginView(View):
    def get(self, request):
        return render(request, 'page-user-login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'page-user-login.html')
        return render(request, 'page-user-login.html')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")

    def post(self, request):
        pass

class Register(View):
    def get(self, request):
        return render(request, 'page-user-register.html')
    def post(self, request):
        user = User.objects.create_user(
            username=request.POST.get("phone"),
            password=request.POST.get("p1")
        )
        kod = randint(100000, 999999)
        Profile.objects.create(
            user = user,
            sms_kod=str(kod),
            shahar=request.POST.get("shahar"),
            davlat=request.POST.get('davlat'),
            ism = request.POST.get("ismi") + " " + request.POST.get("f"),
            tel_raqam=request.POST.get("phone"),
            jins = request.POST.get("gender")
        )
        client = SMSClient(
            api_url="https://notify.eskiz.uz/api/",
            email="1997abdulhamid@gmail.com",
            password="j1YS958itCXn4uEJbZX9bbD7IIp9DOdNbxQ6psdr",
        )

        client._send_sms(
            phone_number=request.POST.get("phone"),
            message=f"{request.POST.get('ismi')} sizning ko'dingiz: {kod}"
        )

        return redirect("tasdiqlash")

class Tasdiqlash(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        profil = Profile.objects.filter(
            sms_kod=request.POST.get("kod"),
            tel_raqam=request.POST.get("tel"),
        )
        if len(profil) == 0:
            return redirect("tasdiqlash")
        profil = profil[0]
        profil.tasdiqlangan = True
        profil.save()
        return redirect("login")

templates/header.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
		{% load static %}
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta name="description" content="Bootstrap e-commerce html template similar to Alibaba">
<meta name="keywords" content="Online template, shop, theme, template, html, css, bootstrap 4">

<title>Website title - bootstrap alistyle html template</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

</head>
<body>

<!-- REMOVE FOLLOWING LINK -->
<a href="http://bootstrap-ecommerce.com/page-themes.html" class="btn btn-dark rounded-pill" style="font-size:13px; z-index:100; position: fixed; bottom:10px; right:10px;">Download theme</a>
<!-- REMOVE  //END -->


<header class="section-header">
<section class="header-main border-bottom">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-xl-2 col-lg-3 col-md-12">
				<a href="http://bootstrap-ecommerce.com" class="brand-wrap">
					<img class="logo" src="images/logo.png?v=2.0">
				</a> <!-- brand-wrap.// -->
			</div>
			<div class="col-xl-6 col-lg-5 col-md-6">
				<form action="#" class="search-header">
					<div class="input-group w-100">
						<select class="custom-select border-right"  name="category_name">
								<option value="">All type</option><option value="codex">Special</option>
								<option value="comments">Only best</option>
								<option value="content">Latest</option>
						</select>
					    <input type="text" class="form-control" placeholder="Search">

					    <div class="input-group-append">
					      <button class="btn btn-primary" type="submit">
					        <i class="fa fa-search"></i> Search
					      </button>
					    </div>
				    </div>
				</form> <!-- search-wrap .end// -->
			</div> <!-- col.// -->
			<div class="col-xl-4 col-lg-4 col-md-6">
				<div class="widgets-wrap float-md-right">
					<div class="widget-header mr-3">
						<a href="#" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-user"></i>
								<span class="notify">3</span>
							</div>
							<small class="text"> My profile </small>
						</a>
					</div>
					<div class="widget-header mr-3">
						<a href="#" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-comment-dots"></i>
								<span class="notify">1</span>
							</div>
							<small class="text"> Message </small>
						</a>
					</div>
					<div class="widget-header mr-3">
						<a href="#" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-store"></i>
							</div>
							<small class="text"> Orders </small>
						</a>
					</div>
					<div class="widget-header">
						<a href="#" class="widget-view">
							<div class="icon-area">
								<i class="fa fa-shopping-cart"></i>
							</div>
							<small class="text"> Cart </small>
						</a>
					</div>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
		</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->



<nav class="navbar navbar-main navbar-expand-lg border-bottom">
<div class="container">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="main_nav">
	<ul class="navbar-nav">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Demo pages </a>
			<div class="dropdown-menu dropdown-large">
				<nav class="row">
					<div class="col-6">
						<a href="page-index-1.html">Home page 1</a>
						<a href="page-index-2.html">Home page 2</a>
						<a href="page-category.html">All category</a>
						<a href="page-listing-large.html">Listing list</a>
						<a href="page-listing-grid.html">Listing grid</a>
						<a href="page-shopping-cart.html">Shopping cart</a>
						<a href="page-detail-product.html">Product detail</a>
						<a href="page-content.html">Page content</a>
						<a href="page-user-login.html">Page login</a>
						<a href="page-user-register.html">Page register</a>
					</div>
					<div class="col-6">
						<a href="page-profile-main.html">Profile main</a>
						<a href="page-profile-orders.html">Profile orders</a>
						<a href="page-profile-seller.html">Profile seller</a>
						<a href="page-profile-wishlist.html">Profile wishlist</a>
						<a href="page-profile-setting.html">Profile setting</a>
						<a href="page-profile-address.html">Profile address</a>
						<a href="rtl-page-index-1.html">RTL home page</a>
						<a href="page-components.html" target="_blank">More components</a>
					</div>
				</nav> <!--  row end .// -->
			</div> <!--  dropdown-menu dropdown-large end.// -->
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#">Ready to ship</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="#">Trade shows</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="#">Services</a>
		</li>
		<li class="nav-item">
		<a class="nav-link" href="#">Sell with us</a>
		</li>
	</ul>
	<ul class="navbar-nav ml-md-auto">
			<li class="nav-item">
			<a class="nav-link" href="#">Get the app</a>
		</li>
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">English</a>
			<div class="dropdown-menu dropdown-menu-right">
			<a class="dropdown-item" href="#">Russian</a>
			<a class="dropdown-item" href="#">French</a>
			<a class="dropdown-item" href="#">Spanish</a>
			<a class="dropdown-item" href="#">Chinese</a>
			</div>
		</li>
		</ul>
	</div> <!-- collapse .// -->
</div> <!-- container .// -->
</nav>

</header> <!-- section-header.// -->

{% block content %}

{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
	<style>
		body {
			background-color: #f2f2f2;
			font-family: Arial, sans-serif;
		}
		.container {
			background-color: #fff;
			border-radius: 5px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
			margin: 100px auto;
			max-width: 500px;
			padding: 20px;
		}
		h1 {
			color: #4CAF50;
			text-align: center;
		}
		label {
			color: #555;
			display: block;
			font-size: 14px;
			font-weight: bold;
			margin-bottom: 5px;
		}
		input[type="text"], input[type="password"] {
			border-radius: 3px;
			border: 1px solid #ccc;
			font-size: 14px;
			padding: 10px;
			width: 95%;
            margin: 10px 5px;
		}
		button {
			background-color: #4CAF50;
			border: none;
			border-radius: 3px;
			color: #fff;
			cursor: pointer;
			font-size: 16px;
			padding: 10px;
			width: 100%;
            margin: 30px 0;
		}
		button:hover {
			background-color: #3e8e41;
		}
	</style>
</head>
<body>
	<div class="container">
		<h1>Tasdiqlash</h1>
		<form method="post" >{% csrf_token %}
			<label for="username">Phone number:</label>
			<input type="text" name="tel" id="username" placeholder="Enter number ...">
			<label for="password">Password:</label>
			<input type="text" name="kod" id="password" placeholder="Enter code ...">
			<button>Login</button>
		</form>
	</div>
</body>
</html>

templates/page-components.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Website title - bootstrap html template</title>

<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">

<!-- jQuery -->
<script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="css/ui.css" rel="stylesheet" type="text/css"/>
<link href="css/responsive.css" rel="stylesheet" />

<!-- custom javascript -->
<script src="js/script.js" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>

<header class="section-header">
<section class="header-main border-bottom">
<div class="container">
	<a href="http://bootstrap-ecommerce.com" class="brand-wrap"><img class="logo" src="images/logo.png"></a>
</div> <!-- container.// -->
</section>
</header> <!-- section-header.// -->


<section class="section-content padding-y">
<div class="container">

<header class="section-heading">
	<h2 class="section-title">All components </h2>
</header><!-- sect-heading -->

<article>

<p>Please open the folder <i class="fa fa-folder text-warning"></i> /<strong><a target="_blank" href="_HTML-Components/">HTML-Components</a></strong> </p>
<p>Each component created in separated file</p>



</article>


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


</body>
</html>

templates/page-detail-product.html
{% extends 'header.html' %}
{% block content %}
<section class="py-3 bg-light">
  <div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Category name</a></li>
        <li class="breadcrumb-item"><a href="#">Sub category</a></li>
        <li class="breadcrumb-item active" aria-current="page">Items</li>
    </ol>
  </div>
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
<div class="container">

<!-- ============================ ITEM DETAIL ======================== -->
	<div class="row">
		<aside class="col-md-6">
<div class="card">
<article class="gallery-wrap"> 
	<div class="img-big-wrap">
	  <div> <a href="#"><img src="{{ mahsulot.media_set.first.rasm.url }}"></a></div>
	</div> <!-- slider-product.// -->
	<div class="thumbs-wrap">
	  <a href="#" class="item-thumb"> <img src="images/items/15.jpg"></a>
	  <a href="#" class="item-thumb"> <img src="images/items/15-1.jpg"></a>
	  <a href="#" class="item-thumb"> <img src="images/items/15-2.jpg"></a>
	  <a href="#" class="item-thumb"> <img src="images/items/15-1.jpg"></a>
	</div> <!-- slider-nav.// -->
</article> <!-- gallery-wrap .end// -->
</div> <!-- card.// -->
		</aside>
		<main class="col-md-6">
<article class="product-info-aside">

<h2 class="title mt-3">{{ mahsulot.nom }} </h2>

<div class="rating-wrap my-3">
	<ul class="rating-stars">
		<li style="width:80%" class="stars-active"> 
			<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
			<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
			<i class="fa fa-star"></i> 
		</li>
		<li>
			<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
			<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
			<i class="fa fa-star"></i> 
		</li>
	</ul>
	<small class="label-rating text-muted">123 reviews</small>
	<small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders </small>
</div> <!-- rating-wrap.// -->

<div class="mb-3"> 
	<var class="price h4">USD {{ mahsulot.narx }}</var>
	<span class="text-muted">USD 562.65 incl. VAT</span> 
</div> <!-- price-detail-wrap .// -->

<p>{{ mahsulot.batafsil }} </p>


<dl class="row">
  <dt class="col-sm-3">Manufacturer</dt>
  <dd class="col-sm-9"><a href="#">{{ mahsulot.brend }}</a></dd>

  <dt class="col-sm-3">Article number</dt>
  <dd class="col-sm-9">596 065</dd>

  <dt class="col-sm-3">Guarantee</dt>
  <dd class="col-sm-9">{{ mahsulot.kafolat }} year</dd>

  <dt class="col-sm-3">Delivery time</dt>
  <dd class="col-sm-9">{{ mahsulot.yetkazish }} days</dd>

  <dt class="col-sm-3">Availabilty</dt>
  <dd class="col-sm-9">in Stock</dd>
</dl>

	<div class="form-row  mt-4">
		<div class="form-group col-md flex-grow-0">
			<div class="input-group mb-3 input-spinner">
			  <div class="input-group-prepend">
			    <button class="btn btn-light" type="button" id="button-plus"> + </button>
			  </div>
			  <input type="text" class="form-control" value="1">
			  <div class="input-group-append">
			    <button class="btn btn-light" type="button" id="button-minus"> &minus; </button>
			  </div>
			</div>
		</div> <!-- col.// -->
		<div class="form-group col-md">
			<a href="#"  class="btn  btn-primary"> 
				<i class="fas fa-shopping-cart"></i> <span class="text">Add to cart</span> 
			</a>
			<a href="#" class="btn btn-light">
        <i class="fas fa-envelope"></i> <span class="text">Contact supplier</span> 
			</a>
		</div> <!-- col.// -->
	</div> <!-- row.// -->

</article> <!-- product-info-aside .// -->
		</main> <!-- col.// -->
	</div> <!-- row.// -->

<!-- ================ ITEM DETAIL END .// ================= -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<div class="container d-flex justify-content-center align-items-center">
<form method="post"> {%csrf_token%}
  <div class="form-group">
    <label for="smileyRating">Your rating</label>
   <div class="rating-container d-flex" id="smileyRating" style="gap: 20px;">
      <input type="radio" name="rating" value="1" style="display:none;">
      <label class="smiley-face" for="smiley1" style="cursor: pointer">&#9785;</label>
      <input type="radio" name="rating" value="2" style="display:none;">
      <label class="smiley-face" for="smiley2" style="cursor: pointer">&#x1F610;</label>
      <input type="radio" name="rating" value="3" style="display:none;">
      <label class="smiley-face" for="smiley3" style="cursor: pointer">&#x1F642;</label>
      <input type="radio" name="rating" value="4" style="display:none;">
      <label class="smiley-face" for="smiley4" style="cursor: pointer">&#x1F600;</label>
      <input type="radio" name="rating" value="5" style="display:none;">
      <label class="smiley-face" for="smiley5" style="cursor: pointer">&#x1F929;</label>
    </div>
  </div>
  <div class="form-group">
      {% for izoh in izohlar %}
    <label for="exampleInputComment1">{{ izoh.matn }}</label>
      {% endfor %}
    <input type="text" class="form-control" id="exampleInputComment1" aria-describedby="commentHelp" placeholder="Enter your comment" name="comment">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div id="selectedRating"></div>

<script>
document.addEventListener("DOMContentLoaded", () => {
    var smileyFaces = document.querySelectorAll('.smiley-face');

    smileyFaces.forEach((face) => {
      face.addEventListener('click', () => {
        // reset transform of all smiley faces
        smileyFaces.forEach((face) => {
          face.style.transform = "none"; // add !important if necessary
        });
        // scale up the clicked smiley face
        face.style.transform = "scale(2)"; // add !important if necessary
      });
    });
  });
</script>
</div>


<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="text-center mb-4">Reviews</h2>
      <hr>
      {% for izoh in izohlar %}
        <div class="row">
          <div class="col-sm-2">
            <div class="text-center">
              {% if izoh.baho == 1 %}
                <span class="smiley-face">&#9785;</span>
              {% elif izoh.baho == 2 %}
                <span class="smiley-face">&#x1F610;</span>
              {% elif izoh.baho == 3 %}
                <span class="smiley-face">&#x1F642;</span>
              {% elif izoh.baho == 4 %}
                <span class="smiley-face">&#x1F600;</span>
              {% elif izoh.baho == 5 %}
                <span class="smiley-face">&#x1F929;</span>
              {% endif %}
            </div>
          </div>
          <div class="col-sm-10">
            <p>{{ izoh.matn }}</p>
             <div class="user d-flex" style="gap: 300px">
                <p><small class="text-muted">{{ izoh.sana }}</small></p>
                <p><small class="text-muted">{{ izoh.profil.ism }}</small></p>
            </div>
          </div>
        </div>
        <hr>
      {% empty %}
        <p>No reviews yet.</p>
      {% endfor %}
    </div>
  </div>
</div>


<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
<div class="container">

<p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

<div class="row justify-content-md-center">
  <div class="col-lg-4 col-sm-6">
<form class="form-row">
    <div class="col-8">
    <input class="form-control" placeholder="Your Email" type="email">
    </div> <!-- col.// -->
    <div class="col-4">
    <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
    </div> <!-- col.// -->
</form>
<small class="form-text">We’ll never share your email address with a third-party. </small>
  </div> <!-- col-md-6.// -->
</div>
  

</div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
  <div class="container">
    <section class="footer-top padding-y-lg text-white">
      <div class="row">
        <aside class="col-md col-6">
          <h6 class="title">Brands</h6>
          <ul class="list-unstyled">
            <li> <a href="#">Adidas</a></li>
            <li> <a href="#">Puma</a></li>
            <li> <a href="#">Reebok</a></li>
            <li> <a href="#">Nike</a></li>
          </ul>
        </aside>
        <aside class="col-md col-6">
          <h6 class="title">Company</h6>
          <ul class="list-unstyled">
            <li> <a href="#">About us</a></li>
            <li> <a href="#">Career</a></li>
            <li> <a href="#">Find a store</a></li>
            <li> <a href="#">Rules and terms</a></li>
            <li> <a href="#">Sitemap</a></li>
          </ul>
        </aside>
        <aside class="col-md col-6">
          <h6 class="title">Help</h6>
          <ul class="list-unstyled">
            <li> <a href="#">Contact us</a></li>
            <li> <a href="#">Money refund</a></li>
            <li> <a href="#">Order status</a></li>
            <li> <a href="#">Shipping info</a></li>
            <li> <a href="#">Open dispute</a></li>
          </ul>
        </aside>
        <aside class="col-md col-6">
          <h6 class="title">Account</h6>
          <ul class="list-unstyled">
            <li> <a href="#"> User Login </a></li>
            <li> <a href="#"> User register </a></li>
            <li> <a href="#"> Account Setting </a></li>
            <li> <a href="#"> My Orders </a></li>
          </ul>
        </aside>
        <aside class="col-md">
          <h6 class="title">Social</h6>
          <ul class="list-unstyled">
            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
          </ul>
        </aside>
      </div> <!-- row.// -->
    </section>  <!-- footer-top.// -->

    <section class="footer-bottom text-center">
    
        <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
        <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
        <br>
    </section>
  </div><!-- //container -->
</footer>

{% endblock %}